version: "3.9"

volumes:
  kong_data: {}

networks:
  kong-net:
    external: false

services:
  kong:
    image: "kong:2.8.1-alpine"
    volumes:
     - ./kong-declarative-config.yml:/tmp/kong-declarative-config.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8001:8001
      - 8444:8444
      - 8443:8443
